"""Per-finding proof-of-concept markdown writeup, suitable for paste into a
HackerOne / Jira / coordinated-disclosure report."""
from __future__ import annotations
import json
from mcpmap.models import ScanResult, Finding, Server


_HEADER = """# Security Finding: {check} — {title}

**Target:** {url}
**Server:** `{server_name} {server_version}`
**Fingerprint:** `{fingerprint}`
**Severity:** {severity_upper} (CVSS {cvss})
**Discovered:** {scan_id} via mcpmap
"""


def _curl_for(check: str, url: str, finding: Finding) -> str:
    """Reconstruct a runnable curl from finding evidence."""
    ev = finding.evidence or {}
    if check == "INJECT-001":
        hits = ev.get("hits") or []
        if not hits:
            return ""
        h = hits[0]
        body = {
            "jsonrpc": "2.0", "id": 1, "method": "tools/call",
            "params": {"name": h["tool"], "arguments": {h["arg"]: h["payload"]}},
        }
        return _curl(url, body)
    if check == "SSRF-001":
        hits = ev.get("hits") or []
        if not hits:
            return ""
        body = {"jsonrpc": "2.0", "id": 1, "method": "resources/read",
                "params": {"uri": hits[0]["uri"]}}
        return _curl(url, body)
    if check in ("AUTH-001", "AUTH-002", "AUTH-003"):
        body = {"jsonrpc": "2.0", "id": 1, "method": "tools/list"}
        return _curl(url, body, extra_headers=_extra_for(check))
    if check == "HONEYPOT-001":
        body = {"jsonrpc": "2.0", "id": 1, "method": "tools/list"}
        return _curl(url, body) + "\n# Repeat 3 times; observe identical Mcp-Session-Id."
    if check in ("POISON-001", "POISON-002", "CVE-001"):
        body = {"jsonrpc": "2.0", "id": 1, "method": "tools/list"}
        return _curl(url, body) + "\n# Inspect the returned tool descriptions / serverInfo.version."
    if check == "TRANSPORT-001":
        return f"curl -s -H 'Accept: text/event-stream' {url}\n# Server speaks deprecated http+sse."
    return _curl(url, {"jsonrpc": "2.0", "id": 1, "method": "tools/list"})


def _extra_for(check: str) -> list[str]:
    if check == "AUTH-002":
        return ["-H 'Authorization: Bearer mcpmap.decoy.unrelated-audience.AAAAAAAA'"]
    if check == "AUTH-003":
        return ["-H 'Origin: https://evil.example'"]
    return []


def _curl(url: str, body: dict, extra_headers: list[str] | None = None) -> str:
    headers = ["-H 'Content-Type: application/json'",
               "-H 'Accept: application/json, text/event-stream'"]
    if extra_headers:
        headers.extend(extra_headers)
    payload = json.dumps(body, indent=2)
    return (f"curl -s -X POST {url} \\\n  "
            + " \\\n  ".join(headers) + " \\\n  "
            + f"-d '{payload}'")


def _server_for(scan: ScanResult, url: str) -> Server | None:
    for s in scan.servers:
        if s.url == url:
            return s
    return None


def render_poc(scan: ScanResult, check_id: str) -> str:
    """Render a markdown PoC for the first matching finding of `check_id`."""
    for url, findings in scan.findings.items():
        for f in findings:
            if f.check != check_id:
                continue
            srv = _server_for(scan, url)
            sname = srv.server_info.name if srv and srv.server_info else "unknown"
            sver = srv.server_info.version if srv and srv.server_info else "?"
            sfp = (srv.fingerprint_id if srv else None) or "unknown"
            parts: list[str] = []
            parts.append(_HEADER.format(
                check=f.check, title=f.title, url=url,
                server_name=sname, server_version=sver, fingerprint=sfp,
                severity_upper=f.severity.value.upper(), cvss=f.cvss,
                scan_id=scan.scan_id,
            ))
            parts.append("## Summary\n")
            parts.append(f.title + "\n")
            parts.append("## Evidence\n")
            ev = f.evidence or {}
            if ev:
                parts.append("```json\n" + json.dumps(ev, indent=2) + "\n```\n")
            else:
                parts.append("(no structured evidence)\n")
            parts.append("## Reproduction\n")
            curl = _curl_for(f.check, url, f)
            if curl:
                parts.append("```bash\n" + curl + "\n```\n")
            if f.repro:
                parts.append(f"**Notes:** {f.repro}\n")
            parts.append("## Remediation\n")
            parts.append((f.remediation or "_(none provided)_") + "\n")
            if f.cve:
                parts.append("## References\n")
                parts.append(f"- {f.cve}\n")
            parts.append("\n---\nGenerated by mcpmap.\n")
            return "\n".join(parts)
    return f"# No findings matched check {check_id}\n"
